---
- name: script for updating the server and installing other packages
  hosts: localhost
  remote_user: ubuntu
  become: true

  tasks:
    - name: update the machine 
      ansible.builtin.apt:
        name: "*"
        state: latest
    
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
    
    - name: Start httpd service
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

    - name: html for server
      ansible.builtin.shell: echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
    
